### ISSUE TITLE
TargetInvocationException and DllNotFoundException: DLL file 'CpuOps.dll' could not be loaded

### ISSUE THREAD

**Issue by njfm0001** [zhongkaifu/Seq2SeqSharp#10]
Hi,

Everytime I open the project, press Debug and try to execute seqlabel to perform a seqlabel task, these two exceptions show up. Thus, I tried to build CpuOps beforehand, but there appeared 6 errors with the same error message:
Error	C2039	'sqrt': is not a member of 'std'	CpuOps	C:\Users\niko_\Desktop\Seq2SeqSharp-master\CpuOps\LayerNormOps.h	90

Any help would be much appreciated.

Kind regards,
Nicolás

**Comment by zhongkaifu** [comment]
Which Windows SDK version did you install ?
