### ISSUE TITLE
FileNotFoundException

### ISSUE THREAD

**Issue by Bernd-H** [zhongkaifu/Seq2SeqSharp#14]
Hi!
I tried to run your program in cmd as followed:
Seq2SeqConsole.exe -TaskName Train -WordVectorSize 512 -HiddenSize 512 -SrcLang en -TgtLang de -TrainCorpusPath ./corpus -ArchType CPU

This raised an Exception:
Unhandled exception: System.IO.FileNotFoundException: The file or assembly "System.Numerics.Vectors, Version = 4.1.4.0, Culture = neutral, PublicKeyToken = b03f5f7f11d50a3a" or a dependency on it was not found. The system can not find the stated file.
   at Seq2SeqConsole.Program.ShowOptions (String [] args, Options options)
   at Seq2SeqConsole.Program.Main (String [] args) in D: \ Seq2SeqSharp_master \ Seq2SeqConsole \ Program.cs: line 67.

I created a new folder in the same directory as the exe, named corpus. In that folder i put two files named train01.de.snt and train01.en.snt which contain 40 sentences each.

Do you know what i did wrong?
Thanks in advance!

**Comment by zhongkaifu** [comment]
Hi @Bernd-H ,

Which version did you use ? The latest version doesn't use "System.Numerics.Vectors" anymore.

**Comment by Bernd-H** [comment]
I think i used the newest release. I got the exe by the following link: https://github.com/zhongkaifu/Seq2SeqSharp/releases/tag/Release_2_0_0_0

**Comment by zhongkaifu** [comment]
I will take a look. For now, you can check out the latest commit from master branch.

**Comment by zhongkaifu** [comment]
I've updated release package. Can you please try it again ?
