### ISSUE TITLE
No handlers have been registered for op relud

### ISSUE THREAD

**Issue by artepic** [zhongkaifu/Seq2SeqSharp#15]
Can you fix 'No handlers have been registered for op relud' ?
i use argument Seq2SeqConsole.exe .... -ProcessorType CPU ...

**Comment by zhongkaifu** [comment]
Hi @artepic 

Did you try to use CPU for training ? Okay, I will add it to support CPU for training.

**Comment by artepic** [comment]
> Hi @artepic
> 
> Did you try to use CPU for training ? Okay, I will add it to support CPU for training.

Hi @zhongkaifu 
now I'm just studying this solution, and I don't have an NVIDIA graphics card on my laptop. I made a fork where I intuitively added this 'relud' support. Maybe right. It's an interesting topic and your code is probably the best c # example I've found. Thank you for updating your code.

**Comment by fabianschalau** [comment]
> 
> 
> Hi @artepic
> 
> Did you try to use CPU for training ? Okay, I will add it to support CPU for training.

Hey @zhongkaifu 
Thank you for this awesome repo!

Im trying to use it on cpu too, do you know in which timespan you will implement it?

**Comment by artepic** [comment]
> > Hi @artepic
> > Did you try to use CPU for training ? Okay, I will add it to support CPU for training.
> 
> Hey @zhongkaifu
> Thank you for this awesome repo!
> 
> Im trying to use it on cpu too, do you know in which timespan you will implement it?

Hi @zhongkaifu 
op relud is fixed here
https://github.com/artepic/Seq2SeqSharp/commit/11bc98e985d7184d841dddf160e4e82e71b9d3ed

some updates are here (in progress)
https://github.com/artepic/Seq2SeqSharp/commits/master

**Comment by zhongkaifu** [comment]
Thank you, @artepic  for your quick fix.

I'm also working on some improvement on it and may push a update this or next week.

**Comment by zhongkaifu** [comment]
Fixed.
