### ISSUE TITLE
VisNNFile is not a valid parameter

### ISSUE THREAD

**Issue by GeorgeS2019** [zhongkaifu/Seq2SeqSharp#23]
Seq2SeqConsole.exe -Task **VisualizeNetwork** **-VisNNFile** Seq2SeqConsole.png -EncoderType Transformer -EncoderLayerDepth 2 -DecoderLayerDepth 2

>VisNNFile is not a valid parameter

Is the Task **VisualizeNetwork**  working?

==> found the network visualization codes.  Is there a plan in future to bring them back?

**Comment by zhongkaifu** [comment]
No, it's not working after Seq2SeqSharp migrated to .NET core, because the library to render graphics doesn't support in .NET core.
