### ISSUE TITLE
SeqSimilarityConsole

### ISSUE THREAD

**Issue by lijianxin520** [zhongkaifu/Seq2SeqSharp#28]
Hello, thank you very much for your constant efforts. Could you please provide an example of "SeqSimilarityConsole"  ?

**Comment by zhongkaifu** [comment]
Hi @lijianxin520 
Basically the input file format for SeqSimilairyConsole looks like
tokenized sentence1 \t tokenized sentence2

And the model will calculate similarity between sentence1 and sentence2, then the output is a score per line, for example: 0.0 ~ 1.0

For model, you need to provide training corpus to train your similarity model.

I will update README file later for it. Let me know if you still have any question.

Thanks
Zhongkai Fu

**Comment by lijianxin520** [comment]
Thank you very much for your help. I'll have a try
