### ISSUE TITLE
Sequence Label task

### ISSUE THREAD

**Issue by bratao** [zhongkaifu/Seq2SeqSharp#3]
Hi @zhongkaifu ,
Congratulations on the new lib. I'm very excited about it!

One question, do you think that it is viable to implement a Sequence Label task using Seq2SeqSharp
? Or RNNSharp is better suited for it?

**Comment by zhongkaifu** [comment]
Thanks @bratao 
Technically, the answer is yes, but CRF layer has not get implmeneted in Seq2SeqSharp yet. Besides this, RNNSharp uses more complex format and features than Seq2SeqSharp, it also has to be migrated (maybe re-implemented) in Seq2SeqSharp.

**Comment by zhongkaifu** [comment]
Seq2SeqSharp supports sequence-labeling task now. You can try Seq2LabelConsole.exe tool
