### ISSUE TITLE
SeqLabelConsole Sequence tag

### ISSUE THREAD

**Issue by lijianxin520** [zhongkaifu/Seq2SeqSharp#30]
Hello, I am learning this framework of yours, and I did not find the problem I met in the help document. I hope you can help me. My training text format is as follows:
世界	n	n	1_n
第	m	m	1_a
八	m	m	-1_m
大	a	a	1_n
奇迹	n	n	1_v
出现	v	v	0_Root

**Comment by zhongkaifu** [comment]
Hi @lijianxin520 

What's problem/error/exception did you get when you ran SeqLabelConsole tool ? What's your question ?


Thanks
Zhongkai Fu

**Comment by lijianxin520** [comment]
Hello, I want to use SeqLabelConsole for Tag training, but the example provides only [Token] \t [Tag],But the format of my corpus is [Token] \t [Token] \t[Token] \t[Tag], what do I do?

**Comment by zhongkaifu** [comment]
There are several different solutions can resolve your question:
 
1. You can try to combine tokens in these three column into a single column. For example:
世界_n_n 1_n
第_m_m 1_a
八_m_m -1_m
大_a_a 1_n
奇迹_n_n 1_v
出现_v_v 0_Root

2. Seq2Seq, SeqClassification and others already support multi-column features, however, SeqLabel has not yet. You can update it to support it. Basically, Tokens (Features) in the same column can be considered as a group of feature, you can update SeqLabel to retrieve features from different groups and then send them to encoder(s).

 
I just found tokens in second column and third column are same. Why ? They look like postag, why these two columns are duplicated ?

Thanks
Zhongkai Fu

**Comment by lijianxin520** [comment]
Thank you very much for your help. I'll have a try. 
For the two columns you see the same characteristics, one is coarse-grained and the other is fine-grained
