### ISSUE TITLE
Release not found: https://github.com/zhongkaifu/Seq2SeqSharp/releases/tag/20210125]

### ISSUE THREAD

**Issue by ysisoftwareiq** [zhongkaifu/Seq2SeqSharp#31]
I tried to get the release https://github.com/zhongkaifu/Seq2SeqSharp/releases/tag/20210125

but got 404 code.

Please let me know where to get the release with medical data corpus and trained models.

I would like to test it and try to use it in our applications.

Your 2 samples of medical text classification are very cool.

Thanks
Yury

**Comment by zhongkaifu** [comment]
Hi @ysisoftwareiq 

I just released a latest version: https://github.com/zhongkaifu/Seq2SeqSharp/releases/tag/RELEASE_2_4 , you can try it out.

Thanks
Zhongkai Fu
