### ISSUE TITLE
Example for Seq2Seq for sequence-classification

### ISSUE THREAD

**Issue by ic202** [zhongkaifu/Seq2SeqSharp#36]
I would love to use Seq2SeqSharp for Multi-intent classification for Chatbot.
Unfortunately I do not understand your examples offered here. I also can't find the test file.
Is there a c# demo project somewhere that explains this problem.

I must mention that my experiences with AI are just using Microsoft ML.Net.

thank you in advance

**Comment by zhongkaifu** [comment]
Hi @ic202 
For classification task, you should use SeqClassificationConsole for it and it uses two input files for training. For your chatbot classification task, one file may contain each turn per line and the other one file contains the corresponding intention of the turn. For example:

File: train.src.snt (each turn per line)
How are you ?
I 'm going to Seattle , WA .
Do you like this movie ?
...

File train.tgt.snt (the corresponding intention)
Greeting
Travel
Entertainment 
...

For test, it just uses one file including turns.

In above example, it only uses a single group feature (word tokens in turn) in train.src.snt. If you have multi feature groups, you can split them by [tab] character. For example:
Do you like this move ? \t [the context of previous turns]

For demos, SeqClassificationConsole currently isn't included into the release package, but I can think about and create a demo project for it. Do you have any demo data set that can be included into the release package ?
