### ISSUE TITLE
Question on Named Entity Recognition

### ISSUE THREAD

**Issue by swidz** [zhongkaifu/Seq2SeqSharp#45]
Hi,
Would it be possible to build a named entity recognition classifier using this project? I saw a 3yrs old post where you replied it was not possible and then a second one posted a year later where you informed that CRF was implemented. 

I am looking for a .net core based tool for training and runing NER tasks. 

Thank you in advance.
Regards,
Sebastian

**Comment by zhongkaifu** [comment]
Yes, Seq2SeqSharp can do it now.
SeqLabelConsole is a command line tool for sequence labeling task (NER can be considered to a typical sequence labeling task). You can download the latest [release package](https://github.com/zhongkaifu/Seq2SeqSharp/releases/tag/RELEASE_2_4_1) and it will show you how to train and test model for it.

**Comment by swidz** [comment]
Thank you
