### ISSUE TITLE
I cannot open the zip files

### ISSUE THREAD

**Issue by piedralaves** [zhongkaifu/Seq2SeqSharp#49]
**Describe the bug**
I cannot open the zip files you provided for data. I mean the Release Packages.

**To Reproduce**
They downloaded propertly but I cannot open them in my desktop. What I am doing wrong?

Thanks a lot. I appreciate your work.

**Comment by zhongkaifu** [comment]
Hi @piedralaves 

Which software did you use to unzip the release package ? I just tried it by 7-zip and it works.

**Comment by piedralaves** [comment]
Yes. I had used winrar. My solution was to repair zip file with winrar instead of open them directly. I can open some of them now. Thanks.
