### ISSUE TITLE
Error: C# 8.0 language feature

### ISSUE THREAD

**Issue by airmouse** [zhongkaifu/Seq2SeqSharp#56]
I am trying to load the .sln and have .Net Core and VS 2019 installed, I have adjusted targets in all .csproj file to `<TargetFramework>net4.0</TargetFramework>` 

But in some files (eg. MoEFeedForward.cs line #62) there are `using` statements that are not compatible with the earlier frameworks, yet it is mentioned directly in the project description that earlier .net versions are supported. Can I use Seq2SeqSharp with .net 4?

**Comment by zhongkaifu** [comment]
If you would like to use earlier .net version, you have to make some changes for back compatible, such as "using" statements -> "using(...) {}" block.

Is there any reason that you don't want to use .NET 6.0 ?
