### ISSUE TITLE
Can some examples for training and evaluation of model be provided?

### ISSUE THREAD

**Issue by erotavlas** [zhongkaifu/Seq2SeqSharp#6]
Hello,
Can you provide example input training files?  In particular I was wondering how to use this for named entity recognition.  How do we represent the tagged entities in the training data?

**Comment by zhongkaifu** [comment]
In homepage, "Data Format" section shows what's the training corpus look like and examples. Seq2SeqSharp is used for text generation, for named entity recognition, you could try RNNSharp (it's CPU only, doesn't support GPU).

**Comment by erotavlas** [comment]
Thank you for the quick reply.  I will take a look at RNNSharp.
