### ISSUE TITLE
Train with general sequences of symbols

### ISSUE THREAD

**Issue by iansmirlis** [zhongkaifu/Seq2SeqSharp#65]
Hello

It's not quite obvious for me from the documentation or the examples if Seq2SeqSharp is capable of handling generic sequences that are not necessarily language words, and if yes, how can achieve this. (I.e. tokens may not be separated by space)

Thanks

**Comment by zhongkaifu** [comment]
Hi @iansmirlis 

Yes, Seq2SeqSharp is able to handle generic sequences. For tokens may not be separated by space, you need to find a tokenizer, such as SentencePiece (https://github.com/google/sentencepiece)  to tokenize your dataset and then process it by Seq2SeqSharp.

For other types of data set, such as image, you need to read pixels from source, build vectors (tensor) for these pixels and then send it to Seq2SeqSharp for processing.

Thanks
Zhongkai Fu

**Comment by iansmirlis** [comment]
Great! Thanks for your prompt reply
