### ISSUE TITLE
Matrix initialization method

### ISSUE THREAD

**Issue by calope12** [zhongkaifu/Seq2SeqSharp#68]
Hi, Zhongkaifu.

I would want to know what is the initialization method used for the matrices.

Thanks a lot.

**Comment by zhongkaifu** [comment]
Hi @calope12 

You could check initialization method here: https://github.com/zhongkaifu/Seq2SeqSharp/blob/da0469c4afc758543c0edbe0d0be1a28ed0f990e/Seq2SeqSharp/Tools/WeightTensor.cs#L186-L206

Thanks
Zhongkai Fu

**Comment by calope12** [comment]
Hi, Zhongkaifu.

I have checked the code and I've drawn the conclusion that it is a Xavier initialization. Could you confirm this, please? Just in case I misunderstood it.

Thanks, again

**Comment by zhongkaifu** [comment]
Yes. You are correct. You could modify or add new initialization in code.

**Comment by calope12** [comment]
Thanks again!
