### ISSUE TITLE
No requirement.txt in this repo

### ISSUE THREAD

**Issue by KangYuan1233** [zhongkaifu/Seq2SeqSharp#69]
**Describe the bug**
I was trying to build the dockerfile from the hugging face, but there is not requirement.txt in this repo, where can I find it

**Comment by zhongkaifu** [comment]
@KangYuan1233 

Seq2SeqSharp doesn't depend on Python package, and it's built by C#, so it doesn't need to have requirement.txt file. You could create an empty requirment.txt file if Docker system needs it.

**Comment by KangYuan1233** [comment]
Thanks.
