### ISSUE TITLE
SeqLabel model backward compatibility is broken by latest update

### ISSUE THREAD

**Issue by zsogitbe** [zhongkaifu/Seq2SeqSharp#76]
**Description:**
The last update and the removal of ClsVocabs everywhere (for example, in SeqLabelModel code) is preventing formerly trained models to load. The problem is the target vocabulary which is now not being set by reading ClsVocabs.

Model backward compatibility is extremely important. The models we train nowadays are trained for several days with a lot of resources and time. We cannot afford to loose all of this because the library is improving. 

**Expected behavior**
Removing clsVocabs to normalize the code and using tgtVocab everywhere is a good improvement, but this should be done in a way that formerly trained models can still be converted or loaded. Solution: add back the clsVocabs serialization and convert old models automatically or provide a console application to convert old models to the new version.

**Comment by zhongkaifu** [comment]
Hi @zsogitbe 

Here is the way to convert your existing trained model to newer format:
1. Load the existing trained model by your modified code.
2. Save the model by calling SaveModel(...) method.

Then you should be able to load the updated model by new code. Let me know if it works.

Thanks
Zhongkai Fu

**Comment by zsogitbe** [comment]
Yes, thank you, I could manage to convert my model (I have also deleted clsVocabs from the model). 

I have added this issue for other users who do not know how to modify the code well and need an other long term solution for model backward compatibility.

**Comment by zsogitbe** [comment]
The code has been updated to support old models automatically.
