### ISSUE TITLE
Any plan to make the model format more "standard"?

### ISSUE THREAD

**Issue by GeorgeS2019** [zhongkaifu/Seq2SeqSharp#8]
It just happens that I set the .Model to be linked to Netron.

I understand that this is not a trivial work, however, I think as more and more users discover this work, it will no longer me who will feedback this :-)

![image](https://user-images.githubusercontent.com/49812372/69099276-a7fe0b80-0a5a-11ea-91ee-20a61e3f8c0c.png)

![image](https://user-images.githubusercontent.com/49812372/69099505-2ce92500-0a5b-11ea-98d4-388856dd80fc.png)

**Comment by zhongkaifu** [comment]
What's the meaning of "standard" ? The different frameworks have different format of their models. :)
