### ISSUE TITLE
biLSTM encoder to LSTM

### ISSUE THREAD

**Issue by piedralaves** [zhongkaifu/Seq2SeqSharp#91]
Hi Zhongkai:

In order to make some metrics over the hidden states we need that the encoder become a unidirectional LSTM instead a bidirectional one. Since Seq2SeqSharp has only a biLSTM, is a good way to provisionally set to zero the hidden state of right to left side? (see the image). If so, what is exactly the part of the code?
Anyway, is there a better way?
![image](https://github.com/user-attachments/assets/1b1ff68a-201b-48f9-ab9b-d49db310bcc3)

Thanks a lot

**Comment by zhongkaifu** [comment]
Hi @piedralaves 

You could check this code:

  [Serializable]
  public class BiEncoder : IEncoder
  {
      private readonly List<LSTMCell> m_forwardEncoders;
      private readonly List<LSTMCell> m_backwardEncoders;
     ....
}

And remove either m_forwardEncoders or m_backwardEncoders from it, and the related codes, then it will become a unidirectional LSTM.


Thanks
Zhongkai Fu

**Comment by piedralaves** [comment]
Thanks.
I will do it that way.

**Comment by piedralaves** [comment]
Hi again,

If I have no backwardOutputs, how to use Add function (which arguments?) 

```
backwardOutputs.Reverse();
layerOutputs.Clear();
for (int j = 0; j < seqLen; j++)
{
    IWeightTensor addW = g.Add(forwardOutputs[j], backwardOutputs[j]);
    layerOutputs.Add(addW);
    
}
```
It needs a float argument v. What is this v?

Thanks a lot

**Comment by zhongkaifu** [comment]
You don't have to call "IWeightTensor addW = g.Add(forwardOutputs[j], backwardOutputs[j]);", and just add either forwardOutputs[j] or backwardOutputs[j] into the layerOutputs.

Can you please point out where is the float argument v as you mentioned?

**Comment by piedralaves** [comment]
![image](https://github.com/user-attachments/assets/a6b5a16d-0302-4d46-bfe1-6f1dd03050f7)

**Comment by zhongkaifu** [comment]
v is a scalar input parameter for one of the Add operators. As I previously replied, you could remove that "Add" step, and just put either forward or backward outputs to the layer outputs.

**Comment by piedralaves** [comment]
Ok, do you think that with this action, putting only forward output to the layer outputs, I dont need to remove all references backward side?, or should I remove all references backward side in the code.

I mean, just putting this:

                ```
backwardOutputs.Reverse();
                layerOutputs.Clear();
                for (int j = 0; j < seqLen; j++)
                {
                    //IWeightTensor addW = g.Add(forwardOutputs[j], backwardOutputs[j]);                    
                    //layerOutputs.Add(addW);
                    layerOutputs.Add(forwardOutputs[j]);
                }
```

It behaves as an unidirectional LSTM. Dont you think?

**Comment by zhongkaifu** [comment]
It should work if you just add forwardOutputs into layerOutputs, but still keep backwardOutputs and related code. However, I would suggest you to remove all codes related to backwardOutputs, because it will save your memory and time during training and inference.

**Comment by piedralaves** [comment]
Thanks a lot.
